/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nwu_hzk_myapplication_JniTest */

#ifndef _Included_com_nwu_hzk_myapplication_JniTest
#define _Included_com_nwu_hzk_myapplication_JniTest
#ifdef __cplusplus
//内部采用C语言的命名风格来编译
extern "C" {
#endif
/*
 * Class:     com_nwu_hzk_myapplication_JniTest
 * Method:    get
 * Signature: ()Ljava/lang/String;
 */

JNIEXPORT jstring JNICALL Java_com_nwu_hzk_myapplication_JniTest_get
  (JNIEnv *, jobject);

/*
 * Class:     com_nwu_hzk_myapplication_JniTest
 * Method:    set
 * Signature: (Ljava/lang/String;)V
 */
 //函数名的格式为Java_包名_类名_方法名，比如jniTest中的set方法，
  /*这里只需要知道Java的String对应的JNI的jstring，
  JNIEXPORT,JNICALL,JNIEnv和jobject都是JNI标准定义的类型或者宏，它们的含义：
    1.JNIEnv*：表示一个指向JNI环境的指针，可以通过他来访问JNI提供的接口方法
    2.jobjct:表示Java对象的this
    3.JNIEXPORT,JNICALL:他们是JNI所定义的宏，可以在jni.h这个头文件中查看
*/
JNIEXPORT void JNICALL Java_com_nwu_hzk_myapplication_JniTest_set
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
